### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by katelinlis** [Tnze/go-mc#137] opened 2021-12-19 06:46 UTC
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x58fdc8]

goroutine 6 [running]:
github.com/Tnze/go-mc/save.(*singleValuePalette).WriteTo(0xc000050520, {0x80c720, 0xc00023e6f0})
	C:/Users/katel/GO-MC/save/palette.go:198 +0x68
github.com/Tnze/go-mc/net/packet.Tuple.WriteTo({0xc000257058, 0x3, 0x3}, {0x80c720, 0xc00023e6f0})
	C:/Users/katel/GO-MC/net/packet/util.go:135 +0x16b
github.com/Tnze/go-mc/save.(*PaletteContainer).WriteTo(0xc00005a200, {0x80c720, 0xc00023e6f0})
	C:/Users/katel/GO-MC/save/palette.go:148 +0x1e5
github.com/Tnze/go-mc/net/packet.Tuple.WriteTo({0xc000257218, 0x3, 0x3}, {0x80c720, 0xc00023e6f0})
	C:/Users/katel/GO-MC/net/packet/util.go:135 +0x16b
github.com/Tnze/go-mc/server.(*Section).WriteTo(0xc0002572e0, {0x80c720, 0xc00023e6f0})
	C:/Users/katel/GO-MC/server/dimension.go:42 +0x1bf
github.com/Tnze/go-mc/server.(*Chunk).Data(0xc000104f60)
	C:/Users/katel/GO-MC/server/dimension.go:86 +0x1a5
github.com/Tnze/go-mc/server.(*Chunk).WriteTo(0xc000104f60, {0x80c720, 0xc00023e6c0})
	C:/Users/katel/GO-MC/server/dimension.go:69 +0x7b
github.com/Tnze/go-mc/net/packet.(*Builder).WriteField(0xc00023e6c0, {0xc000257600, 0x1, 0x1})
	C:/Users/katel/GO-MC/net/packet/builder.go:11 +0xee
github.com/Tnze/go-mc/net/packet.Marshal(0x22, {0xc000257820, 0x4, 0x4})
	C:/Users/katel/GO-MC/net/packet/packet.go:21 +0x1de
github.com/Tnze/go-mc/server.(*SimpleDim).PlayerJoin(0xc00004ec60, 0xc00009c8b8)
	C:/Users/katel/GO-MC/server/dimension.go:147 +0x3ec
github.com/Tnze/go-mc/server.(*Game).AcceptPlayer(0xc000050940, {0xc000086f90, 0xa}, {0x8c, 0xbb, 0x4c, 0xa7, 0x3e, 0x61, 0x4f, ...}, ...)
	C:/Users/katel/GO-MC/server/gameplay.go:77 +0x8c5
github.com/Tnze/go-mc/server.(*Server).acceptConn(0xc000104f90, 0xc00005aa40)
	C:/Users/katel/GO-MC/server/server.go:72 +0x27f
created by github.com/Tnze/go-mc/server.(*Server).Listen
	C:/Users/katel/GO-MC/server/server.go:53 +0x2f3

**Comment by Tnze** [comment] 2021-12-19 07:04
Server framework is in development. And `BlockState` is not implemented.

**Comment by Tnze** [comment] 2021-12-19 07:07
duplicate of #136

**Closed by Tnze** 2021-12-19 07:07 UTC
Labels: bug, duplicate, enhancement
